export const rootActions = {
  CLEAR_STATE: 'CLEAR_STATE',
};

export const authActions = {
  SET_AUTH_IS_LOADING: 'SET_AUTH_IS_LOADING',
  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  SET_AUTH: 'SET_AUTH',
  CLEAR_AUTH: 'CLEAR_AUTH',
};

export const meActions = {
  SET_ME_IS_LOADING: 'SET_ME_IS_LOADING',
  SET_ME_ERROR: 'SET_ME_ERROR',
  SET_ME: 'SET_ME',
};

export const signupActions = {
  SET_SIGNUP_IS_LOADING: 'SET_SIGNUP_IS_LOADING',
  SET_SIGNUP_ERROR: 'SET_SIGNUP_ERROR',
  SET_SIGNUP_HAS_SUCCEEDED: 'SET_SIGNUP_HAS_SUCCEEDED',
};

export const loginActions = {
  SET_LOGIN_IS_LOADING: 'SET_LOGIN_IS_LOADING',
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  SET_LOGIN_HAS_SUCCEEDED: 'SET_LOGIN_HAS_SUCCEEDED',
};

export const startupActions = {
  SET_STARTUP_IS_LOADING: 'SET_STARTUP_IS_LOADING',
  SET_STARTUP_ERROR: 'SET_STARTUP_ERROR',
  SET_STARTUP: 'SET_STARTUP',
  SET_STARTUP_LIST_IS_LOADING: 'SET_STARTUP_LIST_IS_LOADING',
  SET_STARTUP_LIST_ERROR: 'SET_STARTUP_LIST_ERROR',
  SET_STARTUP_LIST: 'SET_STARTUP_LIST',
};

export const teamVacationActions = {
  SET_TEAM_VACATION_IS_LOADING: 'SET_TEAM_VACATION_IS_LOADING',
  SET_TEAM_VACATION_ERROR: 'SET_TEAM_VACATION_ERROR',
  SET_TEAM_VACATION: 'SET_TEAM_VACATION',
  CLEAR_TEAM_VACATION: 'CLEAR_TEAM_VACATION',
};

export const teamActions = {
  TEAM_IS_LOADING: 'TEAM_IS_LOADING',
  TEAM_ERROR: 'TEAM_ERROR',
  TEAM: 'TEAM',
  CLEAR_TEAM: 'CLEAR_TEAM',
};

export const userActions = {
  USER_IS_LOADING: 'USER_IS_LOADING',
  USER_ERROR: 'USER_ERROR',
  USER: 'USER',
  CLEAR_USER: 'CLEAR_USER',
};

export const updateUserActions = {
  UPDATE_USER_IS_LOADING: 'UPDATE_USER_IS_LOADING',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  CLEAR_USER: 'CLEAR_USER',
};

export const createUserActions = {
  CREATE_USER_IS_LOADING: 'CREATE_USER_IS_LOADING',
  CREATE_USER_ERROR: 'CREATE_USER_ERROR',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CLEAR_CREATE_USER: 'CLEAR_CREATE_USER'
};

export const holidayActions = {
  HOLIDAY_IS_LOADING: 'HOLIDAY_IS_LOADING',
  HOLIDAY_ERROR: 'HOLIDAY_ERROR',
  HOLIDAY: 'HOLIDAY',
  CLEAR_HOLIDAY: 'CLEAR_HOLIDAY',
  DELETE_HOLIDAY_IS_LOADING: 'DELETE_HOLIDAY_IS_LOADING',
  DELETE_HOLIDAY_ERROR: 'DELETE_HOLIDAY_ERROR',
  DELETE_HOLIDAY_SUCCESS: 'DELETE_HOLIDAY_SUCCESS',
  CREATE_HOLIDAY_IS_LOADING: 'CREATE_HOLIDAY_IS_LOADING',
  CREATE_HOLIDAY_ERROR: 'CREATE_HOLIDAY_ERROR',
  CREATE_HOLIDAY_SUCCESS: 'CREATE_HOLIDAY_SUCCESS',
};

export const fieldActions = {
  SET_FIELD_IS_LOADING: 'SET_FIELD_IS_LOADING',
  SET_FIELD_ERROR: 'SET_FIELD_ERROR',
  SET_FIELD: 'SET_FIELD',
  SET_FIELD_LIST_IS_LOADING: 'SET_FIELD_LIST_IS_LOADING',
  SET_FIELD_LIST_ERROR: 'SET_FIELD_LIST_ERROR',
  SET_FIELD_LIST: 'SET_FIELD_LIST',
  SET_FIELD_DEGREEDAYS_IS_LOADING: 'SET_FIELD_DEGREEDAYS_IS_LOADING',
  SET_FIELD_DEGREEDAYS_ERROR: 'SET_FIELD_DEGREEDAYS_ERROR',
  SET_FIELD_DEGREEDAYS: 'SET_FIELD_DEGREEDAYS',
  CLEAR_FIELD_DEGREEDAYS: 'CLEAR_FIELD_DEGREEDAYS',
  SET_FIELD_SENSORS_IS_LOADING: 'SET_FIELD_SENSORS_IS_LOADING',
  SET_FIELD_SENSORS_ERROR: 'SET_FIELD_SENSORS_ERROR',
  SET_FIELD_SENSORS: 'SET_FIELD_SENSORS',
  SET_FIELD_READINGS_IS_LOADING: 'SET_FIELD_READINGS_IS_LOADING',
  SET_FIELD_READINGS_ERROR: 'SET_FIELD_READINGS_ERROR',
  SET_FIELD_READINGS: 'SET_FIELD_READINGS',
  // Oli's actions
  FIELD_IS_LOADING: 'FIELD_IS_LOADING',
  FIELD_ERROR: 'FIELD_ERROR',
  FIELD: 'FIELD',
  CLEAR_FIELD: 'CLEAR_FIELD',
  FIELD_LIST_IS_LOADING: 'FIELD_LIST_IS_LOADING',
  FIELD_LIST_ERROR: 'FIELD_LIST_ERROR',
  FIELD_LIST: 'FIELD_LIST',
  CLEAR_FIELD_LIST: 'CLEAR_FIELD_LIST',
  FIELD_SENSOR_IS_LOADING: 'FIELD_SENSOR_IS_LOADING',
  FIELD_SENSOR_ERROR: 'FIELD_SENSOR_ERROR',
  FIELD_SENSOR: 'FIELD_SENSOR',
  CLEAR_FIELD_SENSOR: 'CLEAR_FIELD_SENSOR',
};

export const weatherActions = {
  WEATHER_FORECAST_IS_LOADING: 'WEATHER_FORECAST_IS_LOADING',
  WEATHER_FORECAST_ERROR: 'WEATHER_FORECAST_ERROR',
  WEATHER_FORECAST: 'WEATHER_FORECAST',
  CLEAR_WEATHER_FORECAST: 'CLEAR_WEATHER_FORECAST',
};

export const dataloggerActions = {
  SET_DATALOGGER_IS_LOADING: 'SET_DATALOGGER_IS_LOADING',
  SET_DATALOGGER_ERROR: 'SET_DATALOGGER_ERROR',
  SET_DATALOGGER: 'SET_DATALOGGER',
  SET_DATALOGGER_LIST_IS_LOADING: 'SET_DATALOGGER_LIST_IS_LOADING',
  SET_DATALOGGER_LIST_ERROR: 'SET_DATALOGGER_LIST_ERROR',
  SET_DATALOGGER_LIST: 'SET_DATALOGGER_LIST'
};

export const deviceActions = {
  SET_DEVICE_IS_LOADING: 'SET_DEVICE_IS_LOADING',
  SET_DEVICE_ERROR: 'SET_DEVICE_ERROR',
  SET_DEVICE: 'SET_DEVICE',
  SET_DEVICE_LIST_IS_LOADING: 'SET_DEVICE_LIST_IS_LOADING',
  SET_DEVICE_LIST_ERROR: 'SET_DEVICE_LIST_ERROR',
  SET_DEVICE_LIST: 'SET_DEVICE_LIST'
};

export const mapActions = {
  SET_MAP_IS_LOADING: 'SET_MAP_IS_LOADING',
  SET_MAP_ERROR: 'SET_MAP_ERROR',
  SET_MAP: 'SET_MAP',
  SET_MAP_LIST_IS_LOADING: 'SET_MAP_LIST_IS_LOADING',
  SET_MAP_LIST_ERROR: 'SET_MAP_LIST_ERROR',
  SET_MAP_LIST: 'SET_MAP_LIST'
};

export const monitorActions = {
  SET_MONITOR_IS_LOADING: 'SET_MONITOR_IS_LOADING',
  SET_MONITOR_ERROR: 'SET_MONITOR_ERROR',
  SET_MONITOR: 'SET_MONITOR',
  SET_MONITOR_LIST_IS_LOADING: 'SET_MONITOR_LIST_IS_LOADING',
  SET_MONITOR_LIST_ERROR: 'SET_MONITOR_LIST_ERROR',
  SET_MONITOR_LIST: 'SET_MONITOR_LIST'
};

export const readingActions = {
  SET_READING_IS_LOADING: 'SET_READING_IS_LOADING',
  SET_READING_ERROR: 'SET_READING_ERROR',
  SET_READING: 'SET_READING',
  SET_READING_LIST_IS_LOADING: 'SET_READING_LIST_IS_LOADING',
  SET_READING_LIST_ERROR: 'SET_READING_LIST_ERROR',
  SET_READING_LIST: 'SET_READING_LIST'
};

export const typeMapActions = {
  SET_TYPEMAP_IS_LOADING: 'SET_TYPEMAP_IS_LOADING',
  SET_TYPEMAP_ERROR: 'SET_TYPEMAP_ERROR',
  SET_TYPEMAP: 'SET_TYPEMAP',
  SET_TYPEMAP_LIST_IS_LOADING: 'SET_TYPEMAP_LIST_IS_LOADING',
  SET_TYPEMAP_LIST_ERROR: 'SET_TYPEMAP_LIST_ERROR',
  SET_TYPEMAP_LIST: 'SET_TYPEMAP_LIST'
};

